 "add tabs as spaces, and make them 4 spaces
set autoindent
set smartindent
set smarttab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab

"Respect line wrapping
nnoremap k gk
nnoremap j gj
nnoremap gk k
nnoremap gj j

filetype plugin on
filetype indent on

"SETUP
set visualbell                      "No sounds
set autoread                        "Reload files changed outside vim
set laststatus=2                    "Enabling statusline at all times
if &encoding != 'utf-8'
    set encoding=utf-8              "Necessary to show Unicode glyphs
endif
set noshowmode                      "Don't show the mode(airline is handling this)

imap jj <Esc>                       " Use jj to leave insert mode
set cursorline                      "Highlight the line the cursor is on
set number                          "Line numbers
set incsearch                       "Search acts like search in browser

" Installs vim-plug if not already present
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

"Plugins
call plug#begin()
"TPOPE
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-fugitive'           "Allows git commands
Plug 'tpope/vim-commentary'       "Makes commenting easier
Plug 'tpope/vim-surround'           "Allows changing of surrounding brackets, quotes, etc

Plug 'ctrlpvim/ctrlp.vim'            "Use ctrl-p to switch files

"Airine 
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

"Autoformat
Plug 'chiel92/vim-autoformat'

"Syntax Highlight
Plug 'sheerun/vim-polyglot'

"Style
Plug 'flazz/vim-colorschemes'
Plug 'airblade/vim-gitgutter'

"Netrw
Plug 'tpope/vim-vinegar'

call plug#end()

"Setting the colorscheme
if &t_Co >= 256 || has("gui_running")
    set background=dark
    if !empty(glob('~/.vim/plugged/vim-colorschemes/'))
        colorscheme gruvbox
    endif
endif
if &t_Co > 2 || has("gui_running")
    "switch syntax highlighting on, when the terminal has colors
    syntax on
endif

"Airline
let g:airline_powerline_fonts = 0
let g:airline#extensions#tabline#formatter='unique_tail_improved'
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='deus'

"Ale
let g:airline#extensions#ale#enabled = 1

"AutoFormat
noremap <C-I> :Autoformat<CR>

"Pane Switching
"nnoremap <C-J> <C-W><C-J>
"nnoremap <C-K> <C-W><C-K>
"nnoremap <C-L> :tabl<CR>
"nnoremap <C-H> <C-W><C-H>

"Ctrl-p
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'


"Git Gutter
let g:gitgutter_realtime = 1
set updatetime=500

"Netwr Options
let g:netrw_liststyle = 3
let g:netrw_banner = 0
let g:netrw_preview = 1
let g:netrw_browse_split = 4
let g:netrw_winsize = 20
augroup ProjectDrawer
      autocmd!
        autocmd VimEnter * :Vexplore
augroup END

